apiVersion: v1
kind: Service
metadata:
  name: nginx-jenkins-argocd-service
  labels:
    app: nginx-jenkins-argocd
spec:
  type: NodePort
  selector:
    app: nginx-jenkins-argocd
  ports:
    - port: 8080
      targetPort: 80